version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=senhadev
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_next

networks:
  rabbitmq_go_next:
    driver: bridge